config/routes.rb
Rails.application.routes.draw do

  get "/jquery" => "welcome#jquery"
  get "/ajax" => "welcome#ajax"

  get "/ajaxhtml" => "welcome#ajaxhtml"
  get "/ajaxjs" => "welcome#ajaxjs"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :conferences do
    resources :attendees
  end

  resources :users
  resources :ubikes

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :events # ApiV1::EventsController

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

  end

  root 'conferences#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png",
                    :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml", :s3_host_name => "s3-ap-northeast-1.amazonaws.com"


  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :friendly_id

  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/,
                      :message => "Errrrr"

  STATUS = ["draft", "public"]
  validates_inclusion_of :status, :in => STATUS

  belongs_to :category
  has_many :attendees, :dependent => :destroy

  has_many :groupships
  has_many :groups, :through => :groupships

  has_many :taggings
  has_many :tags, :through => :taggings

  accepts_nested_attributes_for :attendees, :allow_destroy => true, :reject_if => :all_blank

  delegate :name, :to => :category,
                  :prefix => true,
                  :allow_nil => true
  # def category_name
  #   if category
  #     category.name
  #   else
  #     nil
  #   end
  # end

  def to_param
    # "#{self.id}-#{self.name}"
    self.friendly_id
  end

  def tag_list
    self.tags.map{ |t| t.name }.join(",")
  end

  def tag_list=(str)
    arr = str.split(",")

    self.tags = arr.map do |t|
      tag = Tag.find_by_name(t)
      unless tag
        tag = Tag.create!( :name => t )
      end
      tag
    end

  end

end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController

  def index
    @q = Event.ransack(params[:q])
    @events = @q.result(distinct: true)

    if params[:event_id]
      @event = Event.find_by_friendly_id( params[:event_id] )
    else
      @event = Event.new
      @event.status = nil
      @event.friendly_id = SecureRandom.hex(10)
      @event.attendees.build
    end

    gon.tags = Tag.all.map{ |t| t.name }
  end

  def show
    @event = Event.find_by_friendly_id(params[:id])

    if cookies["visit-event-#{@event.id}"]
    else
      cookies["visit-event-#{@event.id}"] = "ya!"
      @event.views_count += 1
      @event.save!
    end

  end

  def create
    @event = Event.new( event_params )

    if @event.save

      HardWorkerJob.perform_later(current_user)
      redirect_to conferences_path
    else
      @q = Event.ransack(params[:q])
      @events = @q.result(distinct: true)

      render "index" # use index.html.erb template
    end
  end

  def update
    @event = Event.find_by_friendly_id(params[:id])

    if params[:destroy_logo] == "1"
      @event.logo = nil
    end

    if @event.update(event_params)
      redirect_to conferences_path
    else
      @events = Event.all
      render "index"
    end
  end

  def destroy
    @event = Event.find_by_friendly_id(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.js # destroy.js.erb
    end

  end

  private

  def event_params
    params.require(:event).permit(:name, :status, :description, :url, :category_id, :logo, :tag_list, :date, :friendly_id,
                    :attendees_attributes => [:id, :name, :_destroy],
                    :group_ids => [] )
  end

end

app/helpers/conferences_helper.rb
module ConferencesHelper

  def event_status_options
    Event::STATUS.map{ |s| [ t(s, :scope => "event.status") ,s] }
  end

  def event_link(event)
    content_tag(:div,
      link_to(event.name, conference_path(event)) +
      tag(:br) +
      event.description,
    :class => "user")
  end

end

app/views/conferences/destroy.js.erb
$("#event-<%= @event.id %>").remove();

app/views/conferences/index.html.erb
<%= search_form_for @q, :url => conferences_path do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>

<hr>

<%
  if params[:event_id]
    url = conference_path(@event)
  else
    url = conferences_path
  end
%>
<%= form_for @event, :url => url do |f| %>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :status %>
  <%= f.select :status, event_status_options, :include_blank => t(:select_prompt) %>

  <%= f.label :friendly_id %>
  <%= f.text_field :friendly_id %>

  <%= f.label :date %>
  <%#= f.date_select :date %>
  <%#= f.date_field :date %>
  <%= f.text_field :date %>


  <%= f.label :tag_list %>
  <%= f.text_field :tag_list %>

  <p>
    <%#= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
    <%= f.select :group_ids, Group.all.map{ |x| [x.name, x.id] }, {}, :multiple => true %>
  </p>

  <% if false %>
    <%= hidden_field_tag "event[group_ids][]", "" %>
    <% Group.all.each do |g| %>
      <%= check_box_tag "event[group_ids][]", g.id, @event.groups.include?(g) %>
      <%= g.name %>
    <% end %>
  <% end %>

  <%= f.label :category_id %>

  <p>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>

  <% if false %>
    <% Category.all.each do |c| %>
      <%= f.radio_button :category_id, c.id %>
      <%= c.name %>
    <% end %>
  <% end %>
  </p>

  <%= f.label :url %>
  <%= f.url_field :url %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <div class="form-group">
    <%= f.label :logo, "LOGO檔案" %>
    <%= f.file_field :logo %>

    <% if @event.logo.exists? %>
      <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
    <% end %>
  </div>

  <%= f.nested_fields_for :attendees do |ff| %>
      <%= ff.label "attendee name" %>
      <%= ff.text_field :name %>
      <%= ff.remove_nested_fields_link %>
  <% end %>
  <%= f.add_nested_fields_link :attendees %>

  <%= f.submit "送出" %>

<% end %>

<p>
  <%= sort_link(@q, :name) %>
  <%= sort_link(@q, :attendees_count) %>
  <%= sort_link(@q, :last_registered_at) %>
</p>

<h2>Conference List</h2>

<table>
<% @events.each do |x| %>
  <tr id="event-<%= x.id %>">
    <td><%= link_to x.name, conference_path(x) %></td>
    <td>
      <% x.tags.each do |t| %>
        <%= link_to t.name, conferences_path( :tag_id => t ) %>
      <% end %>
    </td>
    <td><%= x.category_name %></td>

    <td>
      <%= x.groups.map{ |x| x.name }.join(", ") %>
    </td>
    <td><%= x.url %></td>
    <td><%= link_to "Attendees", conference_attendees_path(x) %>
    <td>
      <%= link_to "Edit", conferences_path( :event_id => x ) %>
    </td>
    <td>
      <%= button_to "Delete", conference_path(x), :remote => true, :method => :delete %>
    </td>
  </tr>
<% end %>
</table>


<script>
  $("#event_date").datepicker({
    format: "yyyy/mm/dd"
  });

  $("#event_category_id").select2();

  $("#event_group_ids").select2();

  $("#event_tag_list").select2({
    tags: gon.tags,
    tokenSeparators: [',', ' ']
  });

</script>

app/views/conferences/show.html.erb
<%= event_link(@event) %>

<%= @event.created_at %>

<hr>

<%= content_for :head do %>
    <%= tag(:meta, :content => @event.name, :property => "og:title") %>
    <%= tag(:meta, :content => @event.description, :property => "og:description") %>
    <%= tag(:meta, :content => "article", :property => "og:type") %>
    <%= tag(:meta, :content => @event.logo.url, :property => "og:image") %>
    <%= tag(:meta, :content => conference_url(@event), :property => "og:url") %>
<% end %>

<%= content_for :footer do %>
  FOO
<% end %>
<%= content_for :sidebar do %>
  <p>Sidebar</p>
<% end %>

<%= @event.name %>

View count: <%= @event.views_count %>

<% if @event.logo.exists? %>
  <%= link_to image_tag(@event.logo.url(:thumb)),
            @event.logo.url %>
<% end %>

<%= simple_format( @event.description ) %>

<%= link_to "Back to index", conferences_path %>