config/routes.rb
Rails.application.routes.draw do

  get "/jquery" => "welcome#jquery"
  get "/ajax" => "welcome#ajax"

  get "/ajaxhtml" => "welcome#ajaxhtml"
  get "/ajaxjs" => "welcome#ajaxjs"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :conferences do
    resources :attendees
  end

  resources :users
  resources :ubikes

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :events # ApiV1::EventsController

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

  end

  root 'conferences#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def ajaxhtml
    sleep(3)
    render :layout => false
  end

  def ajaxjs
    respond_to do |format|
      format.js  # ajaxjs.js.erb
      format.json {
          render :json => { :title => "ABCDEFG",  :time => Time.now }
      }
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_todo.html.erb
<p>
  某 Todo at <%= Time.now %>
  <%= link_to "(remove)", "#" %>
</p>

app/views/welcome/ajax.html.erb
<h2>Ajax demo</h2>

<div id="fountainG">
	<div id="fountainG_1" class="fountainG"></div>
	<div id="fountainG_2" class="fountainG"></div>
	<div id="fountainG_3" class="fountainG"></div>
	<div id="fountainG_4" class="fountainG"></div>
	<div id="fountainG_5" class="fountainG"></div>
	<div id="fountainG_6" class="fountainG"></div>
	<div id="fountainG_7" class="fountainG"></div>
	<div id="fountainG_8" class="fountainG"></div>
</div>

<script id="main-template" type="text/template">
    <h1>Title: {{title}}</h1>
    <h2>at {{time}}</h2>
</script>

<%= link_to "Load HTML", ajaxhtml_path, :id => "load-html" %>
<%= link_to "Remote Script", ajaxjs_path, :remote => true, :id => "remote-js" %>
<%= link_to "Get JSON", ajaxjs_path, :id => "load-json" %>

<div id="content">
  <%= render :partial => "todo" %>
</div>
<hr>
<div id="content2"></div>

<script>
  $("#fountainG").hide();

  $("#load-html").click(function(e){
    e.preventDefault();
    var url = $(this).attr("href");

    $.ajax({
      url: url,
      success: function(response){
        $("#content").html(response);
      },
      error: function() {
        alert("Errrr");
      },
      beforeSend: function(){
        $("#fountainG").show();
      },
      complete: function(){
        $("#fountainG").hide();
      }
    })
  });

  //$("#remote-js").click(function(e){
  //  e.preventDefault();
  //  var url = $(this).attr("href");
  //  $.ajax({
  //    url: url,
  //    dataType: "script"
  //  })
  //})

  $("#load-json").click(function(e){
    e.preventDefault();
    var url = $(this).attr("href");

    var template = $("#main-template").html();

    $.ajax({
      url: url,
      dataType: 'json',
      success: function(data) {
        var html = template.replace("{{title}}", data["title"] );
            html = html.replace("{{time}}", data["time"]);

        $("#content").html(html);
      }
    })
  })

</script>

app/views/welcome/ajaxhtml.html.erb
<h1><%= Time.now %></h1>
<p>from server</p>

app/views/welcome/ajaxjs.js.erb
$("#content").html(" <%=j render(:partial => "todo") %> ");
$("#content2").html("<p>TEST</p>");

app/views/welcome/jquery.html.erb
<h2>jQuery list demo</h2>

<input type="text" id="todo-input">
<input type="submit" id="todo-btn" value="新增">

<ul id="mylist">
  <% ["AAA", "BBB", "CCC", "DDD", "EEE"].each do |x| %>
    <li>
      <%= x %>
      <span>
        <a href="#" class="remove">remove</a>
      </span>
    </li>
  <% end %>
</ul>

<a href="#" id="toggle-list">Toggle</a>

<script>
  $("#mylist").on("click", ".remove", function(){
    //$(this).parent().remove();
    $(this).closest("li").remove();
  })

  $("#todo-btn").click(function(){
    var todo_input = $("#todo-input");
    var todo = todo_input.val();
    todo_input.val("");

    $("#mylist").append("<li>" + todo + ' <a href="#" class="remove">remove</a></li>');
  })

  $("#toggle-list").click(function(){
    $("#mylist").slideToggle();
  })
</script>