config/routes.rb
Rails.application.routes.draw do

  get "/jquery" => "welcome#jquery"
  get "/ajax" => "welcome#ajax"

  get "/ajaxhtml" => "welcome#ajaxhtml"
  get "/ajaxjs" => "welcome#ajaxjs"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :conferences do
    resources :attendees
  end

  resources :users
  resources :ubikes

  scope :path => '/api/v1/', :defaults => { :format => :json }, :module => "api_v1", :as => 'v1' do

    resources :events # ApiV1::EventsController

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

  end

  root 'conferences#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsExercise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>

<%= tag(:body, :class => "#{controller.controller_name} #{controller.action_name}") %>

<%= include_gon %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= t("hello_world") %>

<%= t("admin.event") %>

<%= t( :event, :scope => "admin") %>


<% if current_page?(conferences_path) %>
  this page is conferences_path
<% end %>

<% if current_user %>

<%= t(:hello, :name => current_user.email ) %>

  <%= link_to "Edit Profile", edit_user_path(current_user) %> | 

  <%= link_to "Conferences", conferences_path, :class => "btn btn-primary" + ( (current_page?(conferences_path))? " active" : "" ) %> |
  <%= link_to "UBike", ubikes_path, :class => (current_page?(ubikes_path))? "active" : "" %>

        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
    <% else %>
        <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %> |
        <%= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %>

    <% end %>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <%= yield %>
    </div>
    <div class="col-md-4">
      <%= yield :sidebar %>
    </div>
  </div>
</div>

<div id="footer">

  <%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-TW" %>
  <%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>


  CC | <%= yield :footer %>
</div>

</body>
</html>